version: "3.9"

services:
  lumen:
    build: ./backend-lumen
    container_name: lumen_app
    restart: unless-stopped
    volumes:
      - ./backend-lumen:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis

  node:
    build: ./backend-node
    container_name: node_app
    restart: unless-stopped
    volumes:
      - ./backend-node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - lumen
      - redis
    environment:
      LUMEN_API: http://lumen:9000

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
