name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: lumen_db
          MYSQL_ROOT_PASSWORD: Sql%055705
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -pSql%055705"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
        with:
          path: lumen-react-app

      # --- Node.js setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # --- Node.js caching ---
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: lumen-react-app/backend-node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('lumen-react-app/backend-node/package-lock.json') }}

      # --- Install Node dependencies ---
      - name: Install Node dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
        working-directory: lumen-react-app/backend-node

      # --- Fix permissions ---
      - name: Fix permissions for binaries
        run: chmod -R u+x node_modules/.bin
        working-directory: lumen-react-app/backend-node

      # --- Wait for MySQL ---
      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -p"Sql%055705" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      # --- Create test database ---
      - name: Create test database
        run: |
          mysql -uroot -p"Sql%055705" -h127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS lumen_db;"

      # --- Run Node migrations (if you have them) ---
      - name: Run Node migrations
        run: npm run migrate || echo "No Node migrations"
        working-directory: lumen-react-app/backend-node
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lumen_db
          DB_USERNAME: root
          DB_PASSWORD: Sql%055705

      # --- Run Node Jest tests ---
      - name: Run Node Jest tests
        run: npx jest --runInBand
        working-directory: lumen-react-app/backend-node
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lumen_db
          DB_USERNAME: root
          DB_PASSWORD: Sql%055705

      # --- PHP / Lumen setup ---
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, bcmath, curl

      # --- Composer caching ---
      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: lumen-react-app/backend-lumen/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('lumen-react-app/backend-lumen/composer.lock') }}

      # --- Install Composer dependencies ---
      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction
        working-directory: lumen-react-app/backend-lumen

      # --- Run Lumen migrations ---
      - name: Run Lumen migrations
        run: php artisan migrate --force
        working-directory: lumen-react-app/backend-lumen
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lumen_db
          DB_USERNAME: root
          DB_PASSWORD: Sql%055705

      # --- Run Lumen tests ---
      - name: Run Lumen tests
        run: php artisan test
        working-directory: lumen-react-app/backend-lumen
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lumen_db
          DB_USERNAME: root
          DB_PASSWORD: Sql%055705
