name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      REDIS_CLIENT: array
      LUMEN_API_URL: http://127.0.0.1:9000
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1
      JWT_SECRET: testsecret123

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sqlite, pdo_sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./backend-lumen

      - name: Copy CI environment
        run: cp .env.ci .env
        working-directory: ./backend-lumen

      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --testdox
        working-directory: ./backend-lumen

