name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lumen_test
          MYSQL_USER: lumen
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      # PHP setup
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP dependencies
        working-directory: ./backend-lumen
        run: composer install --no-progress --prefer-dist

      - name: Run Lumen migrations
        working-directory: ./backend-lumen
        run: php artisan migrate --force

      # Start Lumen API
      - name: Start Lumen server
        working-directory: ./backend-lumen
        run: php -S 127.0.0.1:8000 -t public &
      
      - name: Wait for Lumen API
        run: |
          for i in {1..15}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "Lumen is up!"
              break
            fi
            echo "Waiting for Lumen..."
            sleep 2
          done

      - name: Run PHPUnit tests
        working-directory: ./backend-lumen
        run: php ./vendor/bin/phpunit --configuration phpunit.xml

      # Node setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        working-directory: ./backend-node
        run: npm install

      - name: Run Jest tests
        working-directory: ./backend-node
        run: npx jest --runInBand
