name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lumen_test
          MYSQL_USER: lumen
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- Lumen Backend ----------------
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, tokenizer, xml, redis

      - name: Install PHP dependencies
        working-directory: ./backend-lumen
        run: composer install --no-interaction --prefer-dist

      - name: Create CI .env
        working-directory: ./backend-lumen
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=lumen_test" >> .env
          echo "DB_USERNAME=lumen" >> .env
          echo "DB_PASSWORD=secret" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "CACHE_DRIVER=redis" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env

      - name: Run migrations
        working-directory: ./backend-lumen
        run: php artisan migrate --force

      - name: Run PHPUnit tests
        working-directory: ./backend-lumen
        run: php ./vendor/bin/phpunit --configuration phpunit.xml

      # ---------------- Node Caching Layer ----------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        working-directory: ./backend-node
        run: npm install

      - name: Run Jest tests
        working-directory: ./backend-node
        env:
          LUMEN_API_URL: http://127.0.0.1:8000
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: npx jest --runInBand --detectOpenHandles
