name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      REDIS_CLIENT: array
      LUMEN_API_URL: http://127.0.0.1:9000
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1
      JWT_SECRET: gs8j6z7mtGhlm7gheS6OamfeSRij6EAiTa3aY4HsA1HgiEjugIK3sipnsWjcw4v2

    steps:
      - uses: actions/checkout@v3

      # --- PHP / Lumen setup ---
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: sqlite, pdo_sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./backend-lumen

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ./backend-lumen


      - name: Run seeders
        run: php artisan db:seed --force
        working-directory: ./backend-lumen

      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml
        working-directory: ./backend-lumen

      - name: Start Lumen server
        working-directory: ./backend-lumen
        run: php -S 127.0.0.1:9000 -t public &

      - name: Wait for Lumen to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://127.0.0.1:9000/api/health >/dev/null; then
              echo "Lumen is up!"
              exit 0
            fi
            sleep 2
          done
          echo "Lumen did not start in time"
          exit 1

      # --- Node.js setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: backend-node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend-node/package-lock.json') }}

      - name: Install Node dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
        working-directory: ./backend-node

      - name: Fix permissions for binaries
        run: chmod -R u+x node_modules/.bin
        working-directory: ./backend-node

      - name: Run Node Jest tests
        run: npx jest --runInBand
        working-directory: ./backend-node
