name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lumen_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: lumen_db
      DB_USERNAME: root
      DB_PASSWORD: root
      LUMEN_API_URL: http://127.0.0.1:8000
      COMPOSER_PROCESS_TIMEOUT: 0
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_NO_AUDIT: 1
      JWT_SECRET: gs8j6z7mtGhlm7gheS6OamfeSRij6EAiTa3aY4HsA1HgiEjugIK3sipnsWjcw4v2
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_CLIENT: predis

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./backend-lumen

      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -uroot -proot -e "SELECT 1"; do
            sleep 5
          done

      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ./backend-lumen

      - name: Run seeders (optional if needed for tests)
        run: php artisan db:seed --force
        working-directory: ./backend-lumen

      - name: Run PHPUnit tests
        run: php ./vendor/bin/phpunit --configuration phpunit.xml
        working-directory: ./backend-lumen


      # --- Node.js setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: lumen-react-app/backend-node/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('lumen-react-app/backend-node/package-lock.json') }}

      - name: Install Node dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
        working-directory: lumen-react-app/backend-node

      - name: Fix permissions for binaries
        run: chmod -R u+x node_modules/.bin
        working-directory: lumen-react-app/backend-node

      - name: Run Node Jest tests
        run: npx jest --runInBand
        working-directory: lumen-react-app/backend-node
