name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Sql%055705
          MYSQL_DATABASE: lumen_db
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Node.js setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node dependencies (clean)
        run: |
          rm -rf node_modules package-lock.json
          npm install
        working-directory: backend-node

      - name: Fix permissions for binaries
        run: chmod -R u+x node_modules/.bin
        working-directory: backend-node

      - name: Run Node Jest tests
        run: npx jest --runInBand
        working-directory: backend-node



      # --- PHP / Lumen setup ---
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, bcmath, curl

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction
        working-directory: backend-lumen

      - name: Run Lumen tests
        run: php artisan test
        working-directory: backend-lumen
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: lumen_db
          DB_USERNAME: root
          DB_PASSWORD: Sql%055705

  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

